CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_completo" varchar(120) NOT NULL,
  "apellido_paterno" varchar(60) NOT NULL,
  "apellido_materno" varchar(60) NOT NULL,
  "contrasena" varchar(60) NOT NULL,
  "correo_electronico" varchar(60) UNIQUE NOT NULL,
  "telefono" varchar(9),
  "id_tipo_cliente" integer,
  "id_clinica" integer,
  "id_rol_usuario" integer NOT NULL
);

CREATE TABLE "rol_usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "descripcion" text NOT NULL
);

CREATE TABLE "producto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) NOT NULL,
  "codigo_barras" varchar UNIQUE NOT NULL,
  "id_categoria" integer NOT NULL,
  "id_tipo_medicion" integer NOT NULL
);

CREATE TABLE "categoria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "descripcion" text NOT NULL
);

CREATE TABLE "venta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" timestamp(0) NOT NULL,
  "valor_total_impuesto" decimal NOT NULL,
  "valor_total_neto" decimal NOT NULL,
  "valor_total_bruto" decimal NOT NULL,
  "prioridad_urgencia_medica" boolean NOT NULL,
  "id_usuario" integer NOT NULL,
  "id_tipo_documento" integer NOT NULL,
  "id_estado_pago" integer NOT NULL,
  "transaccion_token" varchar,
  "codigo_autorizacion" varchar,
  "fecha_pago" timestamp(0)
);

CREATE TABLE "seguimiento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_seguimiento" varchar UNIQUE NOT NULL,
  "url_etiqueta" text NOT NULL,
  "costo_envio" decimal,
  "fecha_estimada_entrega" date,
  "direccion_destino" varchar,
  "id_comuna_destino" integer,
  "id_estado_seguimiento" integer NOT NULL,
  "id_venta" integer NOT NULL,
  "id_tipo_despacho" integer NOT NULL
);

CREATE TABLE "estado_seguimiento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "descripcion" text NOT NULL
);

CREATE TABLE "tipo_despacho" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "descripcion" text NOT NULL
);

CREATE TABLE "detalle_venta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" integer NOT NULL,
  "valor_unidad" decimal NOT NULL,
  "valor_total" decimal NOT NULL,
  "id_venta" integer NOT NULL,
  "id_producto" integer NOT NULL,
  "id_impuesto" integer NOT NULL
);

CREATE TABLE "impuesto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "porcentaje" integer NOT NULL,
  "descripcion" varchar NOT NULL
);

CREATE TABLE "tipo_cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "porcentaje_utilidad" integer NOT NULL
);

CREATE TABLE "clinica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rut" varchar(8) UNIQUE NOT NULL,
  "digito_verificador" char(1) NOT NULL,
  "nombre" varchar(60) NOT NULL
);

CREATE TABLE "tipo_medicion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "descripcion" text NOT NULL
);

CREATE TABLE "imagen" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(400) UNIQUE NOT NULL,
  "nombre" varchar(60) NOT NULL,
  "id_producto" integer
);

CREATE TABLE "detalle_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor_unidad" decimal NOT NULL,
  "cantidad" integer NOT NULL,
  "id_ingreso_producto" integer NOT NULL,
  "id_producto" integer NOT NULL,
  "id_impuesto" integer NOT NULL
);

CREATE TABLE "tipo_documento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL
);

CREATE TABLE "ingreso_producto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" timestamp(0) NOT NULL,
  "total_compra_neto" decimal NOT NULL,
  "total_compra_bruto" decimal NOT NULL,
  "total_compra_impuesto" decimal,
  "id_bodega" integer NOT NULL
);

CREATE TABLE "estado_pago" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "descripcion" varchar NOT NULL
);

CREATE TABLE "bodega" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "direccion" varchar UNIQUE NOT NULL,
  "id_comuna" integer NOT NULL
);

CREATE TABLE "stock_bodega" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" integer NOT NULL,
  "id_bodega" integer NOT NULL,
  "id_producto" integer NOT NULL
);

CREATE TABLE "region" (
  "id" integer PRIMARY KEY NOT NULL,
  "nombre" varchar(60) UNIQUE NOT NULL
);

CREATE TABLE "comuna" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(60) UNIQUE NOT NULL,
  "id_region" integer NOT NULL
);

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_tipo_cliente") REFERENCES "tipo_cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_clinica") REFERENCES "clinica" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol_usuario") REFERENCES "rol_usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto" ADD FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto" ADD FOREIGN KEY ("id_tipo_medicion") REFERENCES "tipo_medicion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_tipo_documento") REFERENCES "tipo_documento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_estado_pago") REFERENCES "estado_pago" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_comuna_destino") REFERENCES "comuna" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_estado_seguimiento") REFERENCES "estado_seguimiento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_venta") REFERENCES "venta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_tipo_despacho") REFERENCES "tipo_despacho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_venta") REFERENCES "venta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_impuesto") REFERENCES "impuesto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "imagen" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_ingreso_producto") REFERENCES "ingreso_producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_impuesto") REFERENCES "impuesto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingreso_producto" ADD FOREIGN KEY ("id_bodega") REFERENCES "bodega" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bodega" ADD FOREIGN KEY ("id_comuna") REFERENCES "comuna" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_bodega" ADD FOREIGN KEY ("id_bodega") REFERENCES "bodega" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_bodega" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comuna" ADD FOREIGN KEY ("id_region") REFERENCES "region" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Restricción de Clave Única Compuesta para el inventario
ALTER TABLE "stock_bodega" ADD CONSTRAINT "stock_unico_por_bodega" UNIQUE ("id_bodega", "id_producto");

-- Validaciones para la tabla de Ventas
ALTER TABLE "venta" ADD CONSTRAINT "chk_venta_valores_positivos" 
  CHECK ("valor_total_neto" >= 0 AND "valor_total_bruto" >= 0 AND "valor_total_impuesto" >= 0);

-- Validaciones para el Detalle de la Venta
ALTER TABLE "detalle_venta" ADD CONSTRAINT "chk_detalle_venta_cantidad" CHECK ("cantidad" > 0);
ALTER TABLE "detalle_venta" ADD CONSTRAINT "chk_detalle_venta_valores" CHECK ("valor_unidad" >= 0 AND "valor_total" >= 0);

-- Validaciones para la tabla de Ingreso de Productos (Compras a Proveedores)
ALTER TABLE "ingreso_producto" ADD CONSTRAINT "chk_ingreso_valores_positivos" 
  CHECK ("total_compra_neto" >= 0 AND "total_compra_bruto" >= 0 AND "total_compra_impuesto" >= 0);

-- Validaciones para el Detalle de la Compra
ALTER TABLE "detalle_compra" ADD CONSTRAINT "chk_detalle_compra_cantidad" CHECK ("cantidad" > 0);
ALTER TABLE "detalle_compra" ADD CONSTRAINT "chk_detalle_compra_valores" CHECK ("valor_unidad" >= 0);

-- Validaciones para Tablas Paramétricas y Configuración General
ALTER TABLE "impuesto" ADD CONSTRAINT "chk_impuesto_porcentaje" CHECK ("porcentaje" >= 0);
ALTER TABLE "tipo_cliente" ADD CONSTRAINT "chk_utilidad_positiva" CHECK ("porcentaje_utilidad" >= 0);
ALTER TABLE "seguimiento" ADD CONSTRAINT "chk_costo_envio_positivo" CHECK ("costo_envio" >= 0);