CREATE TABLE "usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_usuario" varchar,
  "contrasena" varchar,
  "correo_electronico" varchar,
  "telefono" varchar,
  "id_tipo_cliente" integer,
  "id_clinica" integer,
  "id_rol_usuario" integer
);

CREATE TABLE "rol_usuario" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "descripcion" text
);

CREATE TABLE "producto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "codigo_barras" varchar,
  "id_categoria" integer,
  "id_tipo_medicion" integer
);

CREATE TABLE "categoria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "descripcion" text
);

CREATE TABLE "venta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" timestamp,
  "valor_total_impuesto" decimal,
  "valor_total_neto" decimal,
  "valor_total_bruto" decimal,
  "prioridad_urgencia_medica" boolean,
  "id_usuario" integer,
  "id_tipo_documento" integer,
  "id_estado_pago" integer,
  "transaccion_token" varchar,
  "codigo_autorizacion" varchar,
  "fecha_pago" timestamp
);

CREATE TABLE "seguimiento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numero_seguimiento" varchar,
  "url_etiqueta" text,
  "costo_envio" decimal,
  "fecha_estimada_entrega" date,
  "direccion_destino" varchar,
  "id_comuna_destino" integer,
  "id_estado_seguimiento" integer,
  "id_venta" integer,
  "id_tipo_despacho" integer
);

CREATE TABLE "estado_seguimiento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "descripcion" text
);

CREATE TABLE "tipo_despacho" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "descripcion" text
);

CREATE TABLE "detalle_venta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" integer,
  "valor_unidad" decimal,
  "valor_total" decimal,
  "id_venta" integer,
  "id_producto" integer,
  "id_impuesto" integer
);

CREATE TABLE "impuesto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "porcentaje" integer,
  "descripcion" varchar
);

CREATE TABLE "tipo_cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "porcentaje_utilidad" integer
);

CREATE TABLE "clinica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rut" varchar,
  "nombre" varchar
);

CREATE TABLE "tipo_medicion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "descripcion" text
);

CREATE TABLE "imagen" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar,
  "nombre" varchar,
  "id_producto" integer
);

CREATE TABLE "detalle_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "valor_unidad" decimal,
  "cantidad" integer,
  "fecha_fabricacion" date,
  "fecha_caducidad" date,
  "id_ingreso_producto" integer,
  "id_producto" integer,
  "id_impuesto" integer
);

CREATE TABLE "tipo_documento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "ingreso_producto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" timestamp,
  "total_compra_neto" decimal,
  "total_compra_bruto" decimal,
  "total_compra_impuesto" decimal,
  "id_bodega" integer
);

CREATE TABLE "estado_pago" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "descripcion" varchar
);

CREATE TABLE "bodega" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "direccion" varchar,
  "id_comuna" integer
);

CREATE TABLE "stock_bodega" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cantidad" integer,
  "id_bodega" integer,
  "id_producto" integer
);

CREATE TABLE "region" (
  "id" integer PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "comuna" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "id_region" integer
);

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_tipo_cliente") REFERENCES "tipo_cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_clinica") REFERENCES "clinica" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol_usuario") REFERENCES "rol_usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto" ADD FOREIGN KEY ("id_categoria") REFERENCES "categoria" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "producto" ADD FOREIGN KEY ("id_tipo_medicion") REFERENCES "tipo_medicion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_tipo_documento") REFERENCES "tipo_documento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "venta" ADD FOREIGN KEY ("id_estado_pago") REFERENCES "estado_pago" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_comuna_destino") REFERENCES "comuna" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_estado_seguimiento") REFERENCES "estado_seguimiento" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_venta") REFERENCES "venta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "seguimiento" ADD FOREIGN KEY ("id_tipo_despacho") REFERENCES "tipo_despacho" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_venta") REFERENCES "venta" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_venta" ADD FOREIGN KEY ("id_impuesto") REFERENCES "impuesto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "imagen" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_ingreso_producto") REFERENCES "ingreso_producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalle_compra" ADD FOREIGN KEY ("id_impuesto") REFERENCES "impuesto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ingreso_producto" ADD FOREIGN KEY ("id_bodega") REFERENCES "bodega" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bodega" ADD FOREIGN KEY ("id_comuna") REFERENCES "comuna" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_bodega" ADD FOREIGN KEY ("id_bodega") REFERENCES "bodega" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_bodega" ADD FOREIGN KEY ("id_producto") REFERENCES "producto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comuna" ADD FOREIGN KEY ("id_region") REFERENCES "region" ("id") DEFERRABLE INITIALLY IMMEDIATE;
